###                     Pandas

Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

### Why Use Pandas?
Pandas allows us to analyze big data and make conclusions based on statistical theories.

Pandas can clean messy data sets, and make them readable and relevant.

Relevant data is very important in data science.

### What Can Pandas Do?
Pandas gives you answers about the data. Like:

Is there a correlation between two or more columns?

What is average value?

Max value?

Min value?

Pandas are also able to delete rows that are not relevant, or contains wrong values, like empty or NULL values. This is called cleaning the data.

import pandas as pd

In [ ]:
import pandas as pd

### Data structure in py pandas

The pandas provides two data structure for processing the data 

1 . Series 
2 .Data frame and panel
3 . panel

### series

it is defined as a one dimensional array that is capable of storing various data types

In [2]:
# series

import pandas as pd

In [7]:
x=[1,2,3,4]
var = pd.Series(x)
print(var)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
print(type(var))

<class 'pandas.Series'>

In [9]:
print(var[2])

3

In [14]:
var=pd.Series(x,index=['a','b','c','d'],dtype=float)

In [15]:
print(var)
print(type(var))

a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64
<class 'pandas.Series'>

In [16]:
dic ={"name": ["python","c","c++"],"por":[12,13,1,4],"rank":[1,2,3,4]}

In [17]:
var1 =pd.Series(dic)

print(var1)

name    [python, c, c++]
por       [12, 13, 1, 4]
rank        [1, 2, 3, 4]
dtype: object

In [18]:
s =pd.Series(12,index=[1,2,3,4,5,6,7,8,9])

print(s)
print(type(x))

1    12
2    12
3    12
4    12
5    12
6    12
7    12
8    12
9    12
dtype: int64
<class 'list'>

In [19]:
s1 =pd.Series(12,index=[1,2,3,4,5,6,7,8,9])
s2 =pd.Series(12,index=[1,2,3,4])

print(s1+s2)

1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64

### Data frame

In [20]:
x=[1,2,3,4,5,6,7,8]
var = pd.DataFrame(x)
print(var)
print(type(var))

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8
<class 'pandas.DataFrame'>

In [21]:
# dict
d ={"a":[1,2,3,4,5,6,7],"s":[5,4,8,7,5,74,6]}

var1=pd.DataFrame(d)

print(var1)
print(type(var1))

   a   s
0  1   5
1  2   4
2  3   8
3  4   7
4  5   5
5  6  74
6  7   6
<class 'pandas.DataFrame'>

In [24]:
var1=pd.DataFrame(d,columns=["a"])

print(var1)

   a
0  1
1  2
2  3
3  4
4  5
5  6
6  7

In [26]:
var1=pd.DataFrame(d,columns=["a"],index=["a","b","f","g","r","y","r"])

print(var1)

   a
a  1
b  2
f  3
g  4
r  5
y  6
r  7

In [27]:
d={"a":[1,2,3,4,5],"b":[4,56,7,8,7],"d":[1,2,3,4,5],"d":[4,56,7,8,7]}

var2=pd.DataFrame(d)

print(var2)

print(type(var2))

print(var2["b"][3])

   a   b   d
0  1   4   4
1  2  56  56
2  3   7   7
3  4   8   8
4  5   7   7
<class 'pandas.DataFrame'>
8

In [34]:
#list
list1=[[1,2,3,4,5],[4,56,7,8,7],[1,2,3,4,5],[4,56,7,8,7]]

var2=pd.DataFrame(list1)

print(var2)

print(type(var2))

print(var2[2][3])

   0   1  2  3  4
0  1   2  3  4  5
1  4  56  7  8  7
2  1   2  3  4  5
3  4  56  7  8  7
<class 'pandas.DataFrame'>
7

In [38]:
#series

sr={"s":pd.Series([1,2,3,4,5]),"r":pd.Series([4,56,7,8,7])}

var2=pd.DataFrame(sr)

print(var2)

print(type(var2))

   s   r
0  1   4
1  2  56
2  3   7
3  4   8
4  5   7
<class 'pandas.DataFrame'>

### Arithmetic operation

In [39]:
var=pd.DataFrame({"a":[1,2,3,4],"b":[4,5,6,7]})

var

   a  b
0  1  4
1  2  5
2  3  6
3  4  7

In [43]:
var["c"]=var["a"]+var["b"]
var

   a  b   c
0  1  4   5
1  2  5   7
2  3  6   9
3  4  7  11

In [44]:
var["c"]=var["a"]-var["b"]
var

   a  b  c
0  1  4 -3
1  2  5 -3
2  3  6 -3
3  4  7 -3

In [45]:
var["c"]=var["a"]*var["b"]
var

   a  b   c
0  1  4   4
1  2  5  10
2  3  6  18
3  4  7  28

In [46]:
var["c"]=var["a"]/var["b"]
var

   a  b         c
0  1  4  0.250000
1  2  5  0.400000
2  3  6  0.500000
3  4  7  0.571429

In [47]:
var=pd.DataFrame({"a":[10,20,30,40],"b":[14,15,16,17]})

var

    a   b
0  10  14
1  20  15
2  30  16
3  40  17

In [48]:
var["python"] =var["a"]<=20

In [49]:
var

    a   b  python
0  10  14    True
1  20  15    True
2  30  16   False
3  40  17   False

### insert

In [51]:
var = pd.DataFrame({"A":[1,2,3,45,4],"B":[9,8,5,6,4]})

var

    A  B
0   1  9
1   2  8
2   3  5
3  45  6
4   4  4

In [54]:
var.insert(1,"python",var["A"])
var

    A  python  py  B
0   1       1   1  9
1   2       2   2  8
2   3       3   3  5
3  45      45  45  6
4   4       4   4  4

### csv file